include ../../build/modules.mk

MODULE = gmaps
FILENAME = ${MODULE}.js
SOURCE =  ${MODULE}.js
PRODUCTION = ${PRODUCTION_DIR}/${FILENAME}
DEVELOPMENT = ${DEVELOPMENT_DIR}/${FILENAME}

all:
	cat ${SOURCE} | ${RESOLVE_NAMESPACE} > ${DEVELOPMENT}
	${UGLIFYJS} ${DEVELOPMENT} > ${PRODUCTION}
